/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ActivityLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'incidentId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});
export const IncidentStatus = IDL.Variant({
  'Analyzing' : IDL.Null,
  'Failed' : IDL.Null,
  'Patching' : IDL.Null,
  'Detected' : IDL.Null,
  'Sandboxing' : IDL.Null,
  'Fixed' : IDL.Null,
  'PRSubmitted' : IDL.Null,
});
export const Incident = IDL.Record({
  'id' : IDL.Nat,
  'status' : IncidentStatus,
  'prDescription' : IDL.Text,
  'rcaSummary' : IDL.Text,
  'testCode' : IDL.Text,
  'errorMessage' : IDL.Text,
  'filePath' : IDL.Text,
  'prTitle' : IDL.Text,
  'patchCode' : IDL.Text,
  'errorType' : IDL.Text,
  'lineNumber' : IDL.Nat,
  'timestamp' : IDL.Int,
  'prUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'createIncident' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteIncident' : IDL.Func([IDL.Nat], [], []),
  'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
  'getIncident' : IDL.Func([IDL.Nat], [IDL.Opt(Incident)], ['query']),
  'getIncidentActivity' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ActivityLog)],
      ['query'],
    ),
  'getIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
  'updateIncidentStatus' : IDL.Func(
      [
        IDL.Nat,
        IncidentStatus,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ActivityLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'incidentId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  const IncidentStatus = IDL.Variant({
    'Analyzing' : IDL.Null,
    'Failed' : IDL.Null,
    'Patching' : IDL.Null,
    'Detected' : IDL.Null,
    'Sandboxing' : IDL.Null,
    'Fixed' : IDL.Null,
    'PRSubmitted' : IDL.Null,
  });
  const Incident = IDL.Record({
    'id' : IDL.Nat,
    'status' : IncidentStatus,
    'prDescription' : IDL.Text,
    'rcaSummary' : IDL.Text,
    'testCode' : IDL.Text,
    'errorMessage' : IDL.Text,
    'filePath' : IDL.Text,
    'prTitle' : IDL.Text,
    'patchCode' : IDL.Text,
    'errorType' : IDL.Text,
    'lineNumber' : IDL.Nat,
    'timestamp' : IDL.Int,
    'prUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'createIncident' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteIncident' : IDL.Func([IDL.Nat], [], []),
    'getActivityLog' : IDL.Func([], [IDL.Vec(ActivityLog)], ['query']),
    'getIncident' : IDL.Func([IDL.Nat], [IDL.Opt(Incident)], ['query']),
    'getIncidentActivity' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ActivityLog)],
        ['query'],
      ),
    'getIncidents' : IDL.Func([], [IDL.Vec(Incident)], ['query']),
    'updateIncidentStatus' : IDL.Func(
        [
          IDL.Nat,
          IncidentStatus,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };