/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'id' : bigint,
  'action' : string,
  'incidentId' : bigint,
  'timestamp' : bigint,
  'details' : string,
}
export interface Incident {
  'id' : bigint,
  'status' : IncidentStatus,
  'prDescription' : string,
  'rcaSummary' : string,
  'testCode' : string,
  'errorMessage' : string,
  'filePath' : string,
  'prTitle' : string,
  'patchCode' : string,
  'errorType' : string,
  'lineNumber' : bigint,
  'timestamp' : bigint,
  'prUrl' : string,
}
export type IncidentStatus = { 'Analyzing' : null } |
  { 'Failed' : null } |
  { 'Patching' : null } |
  { 'Detected' : null } |
  { 'Sandboxing' : null } |
  { 'Fixed' : null } |
  { 'PRSubmitted' : null };
export interface _SERVICE {
  'createIncident' : ActorMethod<[string, string, bigint, string], bigint>,
  'deleteIncident' : ActorMethod<[bigint], undefined>,
  'getActivityLog' : ActorMethod<[], Array<ActivityLog>>,
  'getIncident' : ActorMethod<[bigint], [] | [Incident]>,
  'getIncidentActivity' : ActorMethod<[bigint], Array<ActivityLog>>,
  'getIncidents' : ActorMethod<[], Array<Incident>>,
  'updateIncidentStatus' : ActorMethod<
    [bigint, IncidentStatus, string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];