/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ActivityLog {
    id: bigint;
    action: string;
    incidentId: bigint;
    timestamp: bigint;
    details: string;
}
export interface Incident {
    id: bigint;
    status: IncidentStatus;
    prDescription: string;
    rcaSummary: string;
    testCode: string;
    errorMessage: string;
    filePath: string;
    prTitle: string;
    patchCode: string;
    errorType: string;
    lineNumber: bigint;
    timestamp: bigint;
    prUrl: string;
}
export enum IncidentStatus {
    Analyzing = "Analyzing",
    Failed = "Failed",
    Patching = "Patching",
    Detected = "Detected",
    Sandboxing = "Sandboxing",
    Fixed = "Fixed",
    PRSubmitted = "PRSubmitted"
}
export interface backendInterface {
    createIncident(errorType: string, filePath: string, lineNumber: bigint, errorMessage: string): Promise<bigint>;
    deleteIncident(id: bigint): Promise<void>;
    getActivityLog(): Promise<Array<ActivityLog>>;
    getIncident(id: bigint): Promise<Incident | null>;
    getIncidentActivity(incidentId: bigint): Promise<Array<ActivityLog>>;
    getIncidents(): Promise<Array<Incident>>;
    updateIncidentStatus(id: bigint, status: IncidentStatus, rcaSummary: string, patchCode: string, testCode: string, prUrl: string, prTitle: string, prDescription: string): Promise<void>;
}
import type { Incident as _Incident, IncidentStatus as _IncidentStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createIncident(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createIncident(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIncident(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteIncident(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIncident(arg0);
            return result;
        }
    }
    async getActivityLog(): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLog();
            return result;
        }
    }
    async getIncident(arg0: bigint): Promise<Incident | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncident(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncident(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncidentActivity(arg0: bigint): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidentActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidentActivity(arg0);
            return result;
        }
    }
    async getIncidents(): Promise<Array<Incident>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidents();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidents();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateIncidentStatus(arg0: bigint, arg1: IncidentStatus, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIncidentStatus(arg0, to_candid_IncidentStatus_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIncidentStatus(arg0, to_candid_IncidentStatus_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
}
function from_candid_IncidentStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentStatus): IncidentStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Incident_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Incident): Incident {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Incident]): Incident | null {
    return value.length === 0 ? null : from_candid_Incident_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _IncidentStatus;
    prDescription: string;
    rcaSummary: string;
    testCode: string;
    errorMessage: string;
    filePath: string;
    prTitle: string;
    patchCode: string;
    errorType: string;
    lineNumber: bigint;
    timestamp: bigint;
    prUrl: string;
}): {
    id: bigint;
    status: IncidentStatus;
    prDescription: string;
    rcaSummary: string;
    testCode: string;
    errorMessage: string;
    filePath: string;
    prTitle: string;
    patchCode: string;
    errorType: string;
    lineNumber: bigint;
    timestamp: bigint;
    prUrl: string;
} {
    return {
        id: value.id,
        status: from_candid_IncidentStatus_n4(_uploadFile, _downloadFile, value.status),
        prDescription: value.prDescription,
        rcaSummary: value.rcaSummary,
        testCode: value.testCode,
        errorMessage: value.errorMessage,
        filePath: value.filePath,
        prTitle: value.prTitle,
        patchCode: value.patchCode,
        errorType: value.errorType,
        lineNumber: value.lineNumber,
        timestamp: value.timestamp,
        prUrl: value.prUrl
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Analyzing: null;
} | {
    Failed: null;
} | {
    Patching: null;
} | {
    Detected: null;
} | {
    Sandboxing: null;
} | {
    Fixed: null;
} | {
    PRSubmitted: null;
}): IncidentStatus {
    return "Analyzing" in value ? IncidentStatus.Analyzing : "Failed" in value ? IncidentStatus.Failed : "Patching" in value ? IncidentStatus.Patching : "Detected" in value ? IncidentStatus.Detected : "Sandboxing" in value ? IncidentStatus.Sandboxing : "Fixed" in value ? IncidentStatus.Fixed : "PRSubmitted" in value ? IncidentStatus.PRSubmitted : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Incident>): Array<Incident> {
    return value.map((x)=>from_candid_Incident_n2(_uploadFile, _downloadFile, x));
}
function to_candid_IncidentStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentStatus): _IncidentStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentStatus): {
    Analyzing: null;
} | {
    Failed: null;
} | {
    Patching: null;
} | {
    Detected: null;
} | {
    Sandboxing: null;
} | {
    Fixed: null;
} | {
    PRSubmitted: null;
} {
    return value == IncidentStatus.Analyzing ? {
        Analyzing: null
    } : value == IncidentStatus.Failed ? {
        Failed: null
    } : value == IncidentStatus.Patching ? {
        Patching: null
    } : value == IncidentStatus.Detected ? {
        Detected: null
    } : value == IncidentStatus.Sandboxing ? {
        Sandboxing: null
    } : value == IncidentStatus.Fixed ? {
        Fixed: null
    } : value == IncidentStatus.PRSubmitted ? {
        PRSubmitted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
